import { MaterialItem, FenceStyle, CompanyInfo, Estimate } from './types';

export const COMPANY_INFO: CompanyInfo = {
  name: 'Lone Star Fence Works',
  logo: 'https://images.squarespace-cdn.com/content/v1/68b74932e2866a1b202275b6/c7fad08c-3a80-4620-9f80-d0ae036895f0/Revised+LOGO.png?format=1500w',
  phone: '(469) 560-6269',
  email: 'BradenS@LoneStarFenceWorks.com',
  website: 'https://www.lonestarfenceworks.com/',
  address: '1240 Streetman Road, Royse City, Texas 75189'
};

export const MATERIALS: MaterialItem[] = [
  // Wood Structure
  { id: 'w-post-metal-8', name: '2-3/8" x 8\' Sch 20 Metal Post', category: 'Post', unit: 'each', cost: 28.50, description: '.090 wall thickness galvanized', imageUrl: 'https://us.evocdn.io/dealer/1459/catalog/product/images/171-5313-5332-1.webp' },
  { id: 'w-post-metal-9', name: '2-3/8" x 9\' Sch 20 Metal Post', category: 'Post', unit: 'each', cost: 32.75, description: '.090 wall thickness galvanized', imageUrl: 'https://us.evocdn.io/dealer/1459/catalog/product/images/171-5313-5332-1.webp' },
  { id: 'w-post-metal-11', name: '2-3/8" x 11\' Sch 20 Metal Post', category: 'Post', unit: 'each', cost: 38.75, description: '.090 wall thickness galvanized', imageUrl: 'https://us.evocdn.io/dealer/1459/catalog/product/images/171-5313-5332-1.webp' },
  { id: 'w-post-metal-12', name: '2-3/8" x 12\' Sch 20 Metal Post', category: 'Post', unit: 'each', cost: 44.50, description: '.090 wall thickness galvanized', imageUrl: 'https://us.evocdn.io/dealer/1459/catalog/product/images/171-5313-5332-1.webp' },
  { id: 'w-rail-pine-12', name: '2x4-12\' PT Wood Rail (Raw)', category: 'Rail', unit: 'each', cost: 13.50, description: '12ft PT Pine horizontal support', imageUrl: 'https://mobileimages.lowes.com/productimages/99ab7dc6-bf36-4121-9665-15b150f372a2/65213111.jpg' },
  { id: 'w-rail-pine-12-stained', name: '2x4-12\' PT Wood Rail (Pre-Stained)', category: 'Rail', unit: 'each', cost: 17.50, description: '12ft PT Pine horizontal support, pre-stained', imageUrl: 'https://mobileimages.lowes.com/productimages/99ab7dc6-bf36-4121-9665-15b150f372a2/65213111.jpg' },
  { id: 'w-rail-pine-8', name: '2x4-8\' PT Wood Rail (Raw)', category: 'Rail', unit: 'each', cost: 9.75, description: '8ft PT Pine horizontal support', imageUrl: 'https://mobileimages.lowes.com/productimages/99ab7dc6-bf36-4121-9665-15b150f372a2/65213111.jpg' },
  { id: 'w-rail-pine-8-stained', name: '2x4-8\' PT Wood Rail (Pre-Stained)', category: 'Rail', unit: 'each', cost: 12.75, description: '8ft PT Pine horizontal support, pre-stained', imageUrl: 'https://mobileimages.lowes.com/productimages/99ab7dc6-bf36-4121-9665-15b150f372a2/65213111.jpg' },
  { id: 'w-rail-w-cedar-12', name: '2x4-12\' Western Red Cedar Rail (Raw)', category: 'Rail', unit: 'each', cost: 24.75, description: '12ft Western Red Cedar horizontal support', imageUrl: 'https://mobileimages.lowes.com/productimages/99ab7dc6-bf36-4121-9665-15b150f372a2/65213111.jpg' },
  { id: 'w-rail-w-cedar-12-stained', name: '2x4-12\' Western Red Cedar Rail (Pre-Stained)', category: 'Rail', unit: 'each', cost: 29.75, description: '12ft Western Red Cedar horizontal support, pre-stained', imageUrl: 'https://mobileimages.lowes.com/productimages/99ab7dc6-bf36-4121-9665-15b150f372a2/65213111.jpg' },
  { id: 'w-rail-w-cedar-8', name: '2x4-8\' Western Red Cedar Rail (Raw)', category: 'Rail', unit: 'each', cost: 16.50, description: '8ft Western Red Cedar horizontal support', imageUrl: 'https://mobileimages.lowes.com/productimages/99ab7dc6-bf36-4121-9665-15b150f372a2/65213111.jpg' },
  { id: 'w-rail-w-cedar-8-stained', name: '2x4-8\' Western Red Cedar Rail (Pre-Stained)', category: 'Rail', unit: 'each', cost: 19.50, description: '8ft Western Red Cedar horizontal support, pre-stained', imageUrl: 'https://mobileimages.lowes.com/productimages/99ab7dc6-bf36-4121-9665-15b150f372a2/65213111.jpg' },
  { id: 'w-rail-j-cedar-12', name: '2x4-12\' Japanese Cedar Rail (Raw)', category: 'Rail', unit: 'each', cost: 19.50, description: '12ft Japanese Cedar horizontal support', imageUrl: 'https://mobileimages.lowes.com/productimages/99ab7dc6-bf36-4121-9665-15b150f372a2/65213111.jpg' },
  { id: 'w-rail-j-cedar-12-stained', name: '2x4-12\' Japanese Cedar Rail (Pre-Stained)', category: 'Rail', unit: 'each', cost: 23.50, description: '12ft Japanese Cedar horizontal support, pre-stained', imageUrl: 'https://mobileimages.lowes.com/productimages/99ab7dc6-bf36-4121-9665-15b150f372a2/65213111.jpg' },
  { id: 'w-rail-j-cedar-8', name: '2x4-8\' Japanese Cedar Rail (Raw)', category: 'Rail', unit: 'each', cost: 13.25, description: '8ft Japanese Cedar horizontal support', imageUrl: 'https://mobileimages.lowes.com/productimages/99ab7dc6-bf36-4121-9665-15b150f372a2/65213111.jpg' },
  { id: 'w-rail-j-cedar-8-stained', name: '2x4-8\' Japanese Cedar Rail (Pre-Stained)', category: 'Rail', unit: 'each', cost: 16.25, description: '8ft Japanese Cedar horizontal support, pre-stained', imageUrl: 'https://mobileimages.lowes.com/productimages/99ab7dc6-bf36-4121-9665-15b150f372a2/65213111.jpg' },
  { id: 'w-rot-board-12', name: '2x6-12\' PT Pine Rot Board (Raw)', category: 'Rail', unit: 'each', cost: 16.50, description: '2x6-12ft Bottom PT Pine rot board', imageUrl: 'https://mobileimages.lowes.com/productimages/99ab7dc6-bf36-4121-9665-15b150f372a2/65213111.jpg' },
  { id: 'w-rot-board-12-stained', name: '2x6-12\' PT Pine Rot Board (Pre-Stained)', category: 'Rail', unit: 'each', cost: 21.50, description: '2x6-12ft Bottom PT Pine rot board, pre-stained', imageUrl: 'https://mobileimages.lowes.com/productimages/99ab7dc6-bf36-4121-9665-15b150f372a2/65213111.jpg' },
  { id: 'w-rot-board-8', name: '2x6-8\' PT Pine Rot Board (Raw)', category: 'Rail', unit: 'each', cost: 11.50, description: '2x6-8ft Bottom PT Pine rot board', imageUrl: 'https://mobileimages.lowes.com/productimages/99ab7dc6-bf36-4121-9665-15b150f372a2/65213111.jpg' },
  { id: 'w-rot-board-8-stained', name: '2x6-8\' PT Pine Rot Board (Pre-Stained)', category: 'Rail', unit: 'each', cost: 15.50, description: '2x6-8ft Bottom PT Pine rot board, pre-stained', imageUrl: 'https://mobileimages.lowes.com/productimages/99ab7dc6-bf36-4121-9665-15b150f372a2/65213111.jpg' },
  { id: 'w-rot-board-16', name: '2-6-16\' PT Pine Rot Board (Raw)', category: 'Rail', unit: 'each', cost: 22.50, description: '2x6-16ft Bottom PT Pine rot board', imageUrl: 'https://mobileimages.lowes.com/productimages/99ab7dc6-bf36-4121-9665-15b150f372a2/65213111.jpg' },
  { id: 'w-rot-board-16-stained', name: '2-6-16\' PT Pine Rot Board (Pre-Stained)', category: 'Rail', unit: 'each', cost: 28.50, description: '2x6-16ft Bottom PT Pine rot board, pre-stained', imageUrl: 'https://mobileimages.lowes.com/productimages/99ab7dc6-bf36-4121-9665-15b150f372a2/65213111.jpg' },
  { id: 'w-picket-pine', name: '1x5.5-6\' Pine Picket (Raw)', category: 'Picket', unit: 'each', cost: 2.85, description: 'Pressure-treated pine', imageUrl: 'https://images.thdstatic.com/productImages/1ba2667d-0dc4-4b85-b047-7a4660cfe8a7/svn/pressure-treated-lumber-194354-64_1000.jpg' },
  { id: 'w-picket-pine-stained', name: '1x5.5-6\' Pine Picket (Pre-Stained)', category: 'Picket', unit: 'each', cost: 4.85, description: 'Pressure-treated pine, pre-stained', imageUrl: 'https://images.thdstatic.com/productImages/1ba2667d-0dc4-4b85-b047-7a4660cfe8a7/svn/pressure-treated-lumber-194354-64_1000.jpg' },
  { id: 'w-picket-pine-8', name: '1x5.5-8\' Pine Picket (Raw)', category: 'Picket', unit: 'each', cost: 3.95, description: 'Pressure-treated pine, 8ft tall', imageUrl: 'https://images.thdstatic.com/productImages/1ba2667d-0dc4-4b85-b047-7a4660cfe8a7/svn/pressure-treated-lumber-194354-64_1000.jpg' },
  { id: 'w-picket-pine-8-stained', name: '1x5.5-8\' Pine Picket (Pre-Stained)', category: 'Picket', unit: 'each', cost: 5.95, description: 'Pressure-treated pine, 8ft tall, pre-stained', imageUrl: 'https://images.thdstatic.com/productImages/1ba2667d-0dc4-4b85-b047-7a4660cfe8a7/svn/pressure-treated-lumber-194354-64_1000.jpg' },
  
  { id: 'w-picket-w-cedar', name: '1x5.5-6\' Western Red Cedar Picket (Raw)', category: 'Picket', unit: 'each', cost: 4.25, description: 'Premium Western Red Cedar', imageUrl: 'https://patriotfencekc.com/wp-content/gallery/aluminu/4-tall-solid-cedar-privacy-1x6x4.jpeg' },
  { id: 'w-picket-w-cedar-stained', name: '1x5.5-6\' Western Red Cedar Picket (Pre-Stained)', category: 'Picket', unit: 'each', cost: 6.25, description: 'Premium Western Red Cedar, pre-stained', imageUrl: 'https://patriotfencekc.com/wp-content/gallery/aluminu/4-tall-solid-cedar-privacy-1x6x4.jpeg' },
  { id: 'w-picket-w-cedar-8', name: '1x5.5-8\' Western Red Cedar Picket (Raw)', category: 'Picket', unit: 'each', cost: 5.95, description: 'Premium Western Red Cedar, 8ft tall', imageUrl: 'https://patriotfencekc.com/wp-content/gallery/aluminu/4-tall-solid-cedar-privacy-1x6x4.jpeg' },
  { id: 'w-picket-w-cedar-8-stained', name: '1x5.5-8\' Western Red Cedar Picket (Pre-Stained)', category: 'Picket', unit: 'each', cost: 7.95, description: 'Premium Western Red Cedar, 8ft tall, pre-stained', imageUrl: 'https://patriotfencekc.com/wp-content/gallery/aluminu/4-tall-solid-cedar-privacy-1x6x4.jpeg' },
  
  { id: 'w-picket-j-cedar', name: '1x5.5-6\' Japanese Cedar Picket (Raw)', category: 'Picket', unit: 'each', cost: 3.75, description: 'Japanese Cedar (Sugi)', imageUrl: 'https://m.media-amazon.com/images/I/41b0RJrZRKL.jpg' },
  { id: 'w-picket-j-cedar-stained', name: '1x5.5-6\' Japanese Cedar Picket (Pre-Stained)', category: 'Picket', unit: 'each', cost: 5.75, description: 'Japanese Cedar (Sugi), pre-stained', imageUrl: 'https://m.media-amazon.com/images/I/41b0RJrZRKL.jpg' },
  { id: 'w-picket-j-cedar-8', name: '1x5.5-8\' Japanese Cedar Picket (Raw)', category: 'Picket', unit: 'each', cost: 5.25, description: 'Japanese Cedar (Sugi), 8ft tall', imageUrl: 'https://m.media-amazon.com/images/I/41b0RJrZRKL.jpg' },
  { id: 'w-picket-j-cedar-8-stained', name: '1x5.5-8\' Japanese Cedar Picket (Pre-Stained)', category: 'Picket', unit: 'each', cost: 7.25, description: 'Japanese Cedar (Sugi), 8ft tall, pre-stained', imageUrl: 'https://m.media-amazon.com/images/I/41b0RJrZRKL.jpg' },
  
  { id: 'w-picket-1x4', name: '1x4-4\' Wood Picket', category: 'Picket', unit: 'each', cost: 2.45, description: 'Standard pine picket', imageUrl: 'https://m.media-amazon.com/images/I/41b0RJrZRKL.jpg' },
  
  // Chain Link Structure
  { id: 'cl-post-term-5', name: '2-3/8" x 5\' Terminal Post', category: 'Post', unit: 'each', cost: 26.00, description: 'For 3ft fence' },
  { id: 'cl-post-term-6', name: '2-3/8" x 6\' Terminal Post', category: 'Post', unit: 'each', cost: 32.00, description: 'For 4ft fence', imageUrl: 'https://us.evocdn.io/dealer/1459/catalog/product/images/171-5313-5332-1.webp' },
  { id: 'cl-post-term-7', name: '2-3/8" x 7\' Terminal Post', category: 'Post', unit: 'each', cost: 38.00, description: 'For 5ft fence' },
  { id: 'cl-post-term-8', name: '2-3/8" x 8\' Terminal Post', category: 'Post', unit: 'each', cost: 44.00, description: 'For 6ft fence' },
  
  { id: 'cl-post-line-res-5', name: '1-5/8" x 5\' Line Post (Residential)', category: 'Post', unit: 'each', cost: 18.50, description: 'For 3ft fence' },
  { id: 'cl-post-line-res-6', name: '1-5/8" x 6\' Line Post (Residential)', category: 'Post', unit: 'each', cost: 22.50, description: 'For 4ft fence', imageUrl: 'https://images.thdstatic.com/productImages/697ae182-412a-4187-b72a-1547bd41ac71/svn/fencer-wire-chain-link-fence-accessories-lbp-10x1f58-64_600.jpg' },
  { id: 'cl-post-line-res-7', name: '1-5/8" x 7\' Line Post (Residential)', category: 'Post', unit: 'each', cost: 26.50, description: 'For 5ft fence' },
  { id: 'cl-post-line-res-8', name: '1-5/8" x 8\' Line Post (Residential)', category: 'Post', unit: 'each', cost: 30.50, description: 'For 6ft fence' },
  
  { id: 'cl-post-line-comm-5', name: '1-7/8" x 5\' Line Post (Commercial)', category: 'Post', unit: 'each', cost: 32.50, description: 'For 3ft fence' },
  { id: 'cl-post-line-comm-6', name: '1-7/8" x 6\' Line Post (Commercial)', category: 'Post', unit: 'each', cost: 38.50, description: 'For 4ft fence', imageUrl: 'https://images.thdstatic.com/productImages/697ae182-412a-4187-b72a-1547bd41ac71/svn/fencer-wire-chain-link-fence-accessories-lbp-10x1f58-64_600.jpg' },
  { id: 'cl-post-line-comm-7', name: '1-7/8" x 7\' Line Post (Commercial)', category: 'Post', unit: 'each', cost: 44.50, description: 'For 5ft fence' },
  { id: 'cl-post-line-comm-8', name: '1-7/8" x 8\' Line Post (Commercial)', category: 'Post', unit: 'each', cost: 50.50, description: 'For 6ft fence' },
  { id: 'cl-rail-top', name: '1-3/8" x 21\' Top Rail (Residential)', category: 'Rail', unit: 'each', cost: 68.25, description: '21ft horizontal top pipe', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvhspKHpyyyB9YIYToMXfD01oTeYOHnSnpqA&s' },
  { id: 'cl-rail-top-comm', name: '1-5/8" x 21\' Top Rail (Commercial)', category: 'Rail', unit: 'each', cost: 99.75, description: '21ft commercial grade horizontal rail', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvhspKHpyyyB9YIYToMXfD01oTeYOHnSnpqA&s' },
  { id: 'cl-rail-bottom', name: '1-5/8" x 21\' Bottom Rail (Commercial)', category: 'Rail', unit: 'each', cost: 99.75, description: '21ft used instead of tension wire' },
  // Residential Mesh (11 Gauge)
  { id: 'cl-mesh-res-3', name: '11ga Galv Mesh 3\' (Residential)', category: 'Picket', unit: 'lf', cost: 3.25, description: '3ft residential grade fabric' },
  { id: 'cl-mesh-res-4', name: '11ga Galv Mesh 4\' (Residential)', category: 'Picket', unit: 'lf', cost: 4.50, description: '4ft residential grade fabric' },
  { id: 'cl-mesh-res-5', name: '11ga Galv Mesh 5\' (Residential)', category: 'Picket', unit: 'lf', cost: 5.75, description: '5ft residential grade fabric' },
  { id: 'cl-mesh-res-6', name: '11ga Galv Mesh 6\' (Residential)', category: 'Picket', unit: 'lf', cost: 6.75, description: '6ft residential grade fabric' },
  // Commercial Mesh (9 Gauge)
  { id: 'cl-mesh-comm-3', name: '9ga Galv Mesh 3\' (Commercial)', category: 'Picket', unit: 'lf', cost: 4.25, description: '3ft commercial grade fabric' },
  { id: 'cl-mesh-comm-4', name: '9ga Galv Mesh 4\' (Commercial)', category: 'Picket', unit: 'lf', cost: 5.50, description: '4ft commercial grade fabric' },
  { id: 'cl-mesh-comm-5', name: '9ga Galv Mesh 5\' (Commercial)', category: 'Picket', unit: 'lf', cost: 6.75, description: '5ft commercial grade fabric' },
  { id: 'cl-mesh-comm-6', name: '9ga Galv Mesh 6\' (Commercial)', category: 'Picket', unit: 'lf', cost: 7.75, description: '6ft commercial grade fabric', imageUrl: 'https://image.made-in-china.com/318f0j00YTqfkIjPqHgb/-mp4.webp' },
  { id: 'cl-tension-wire', name: 'Bottom Tension Wire', category: 'Hardware', unit: 'lf', cost: 0.65, description: 'Prevents mesh lifting', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_amSlsfxUJJ0Uvy1zk-95EIbBcJb3FEuDHQ&s' },
  { id: 'cl-hw-boulevard', name: 'Boulevard Bracket (1-7/8" x 1-5/8")', category: 'Hardware', unit: 'each', cost: 8.50, description: 'Connects bottom rail to line posts' },
  { id: 'cl-hw-brace-comm', name: '1-7/8" Brace Band', category: 'Hardware', unit: 'each', cost: 2.25, description: 'Commercial brace band' },
  { id: 'cl-hw-cup-comm', name: '1-5/8" Rail End Cup', category: 'Hardware', unit: 'each', cost: 3.75, description: 'For connecting rail to terminal posts' },
  { id: 'cl-hw-cup-res', name: '1-3/8" Rail End Cup', category: 'Hardware', unit: 'each', cost: 3.25, description: 'For connecting rail to terminal posts' },
  { id: 'cl-hw-tension-bar-3', name: "3' Tension Bar", category: 'Hardware', unit: 'each', cost: 8.50 },
  { id: 'cl-hw-tension-bar-4', name: "4' Tension Bar", category: 'Hardware', unit: 'each', cost: 10.50 },
  { id: 'cl-hw-tension-bar-5', name: "5' Tension Bar", category: 'Hardware', unit: 'each', cost: 12.50 },
  { id: 'cl-hw-tension-bar-6', name: "6' Tension Bar", category: 'Hardware', unit: 'each', cost: 14.50 },
  { id: 'cl-hw-tension-band-238', name: '2-3/8" Tension Band', category: 'Hardware', unit: 'each', cost: 1.85 },
  { id: 'cl-hw-brace-band-238', name: '2-3/8" Brace Band', category: 'Hardware', unit: 'each', cost: 1.95 },
  { id: 'cl-hw-dome-238', name: '2-3/8" Dome Cap', category: 'Hardware', unit: 'each', cost: 4.50 },
  { id: 'cl-hw-loop-178', name: '1-7/8" Loop Cap', category: 'Hardware', unit: 'each', cost: 3.75 },
  { id: 'cl-hw-loop-158', name: '1-5/8" Loop Cap', category: 'Hardware', unit: 'each', cost: 3.25 },
  { id: 'cl-hw-ez-tie-138', name: '1-3/8" EZ Tie (Rail)', category: 'Hardware', unit: 'each', cost: 0.75 },
  { id: 'cl-hw-ez-tie-158', name: '1-5/8" EZ Tie (Rail/Post)', category: 'Hardware', unit: 'each', cost: 0.85 },
  { id: 'cl-hw-ez-tie-178', name: '1-7/8" EZ Tie (Line Post)', category: 'Hardware', unit: 'each', cost: 0.95 },
  { id: 'cl-hw-hog-ring', name: 'Hog Ring', category: 'Hardware', unit: 'each', cost: 0.15 },
  
  // Metal Structure
  { id: 'm-post-2x2-5', name: '2x2 x 5\' Wrought Iron Post', category: 'Post', unit: 'each', cost: 32.00, description: 'For 3ft fence' },
  { id: 'm-post-2x2-6', name: '2x2 x 6\' Wrought Iron Post', category: 'Post', unit: 'each', cost: 38.00, description: 'For 4ft fence', imageUrl: 'https://quickshipaluminumfence.com/store/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/a/b/abp27b_black-aluminum-blank-post-2in-x-2in-x7ft_02.jpg' },
  { id: 'm-post-2x2-7', name: '2x2 x 7\' Wrought Iron Post', category: 'Post', unit: 'each', cost: 44.00, description: 'For 5ft fence' },
  { id: 'm-post-2x2-8', name: '2x2 x 8\' Wrought Iron Post', category: 'Post', unit: 'each', cost: 50.00, description: 'For 6ft fence' },
  { id: 'm-post-2x2-9', name: '2x2 x 9\' Wrought Iron Post', category: 'Post', unit: 'each', cost: 56.00, description: 'For 7ft fence or 6ft gate' },
  { id: 'm-post-2x2-10', name: '2x2 x 10\' Wrought Iron Post', category: 'Post', unit: 'each', cost: 62.00, description: 'For 7ft gate' },
  { id: 'm-post-4x4-6', name: '4x4 x 6\' Wrought Iron Post', category: 'Post', unit: 'each', cost: 105.00, description: 'Drive gate post for 3ft fence' },
  { id: 'm-post-4x4-7', name: '4x4 x 7\' Wrought Iron Post', category: 'Post', unit: 'each', cost: 110.00, description: 'Drive gate post for 4ft fence' },
  { id: 'm-post-4x4-8', name: '4x4 x 8\' Wrought Iron Post', category: 'Post', unit: 'each', cost: 115.00, description: 'Drive gate post for 5ft fence' },
  { id: 'm-post-4x4-9', name: '4x4 x 9\' Wrought Iron Post', category: 'Post', unit: 'each', cost: 125.00, description: 'Drive gate post for 6-7ft fence' },
  { id: 'm-post-4x4-10', name: '4x4 x 10\' Wrought Iron Post', category: 'Post', unit: 'each', cost: 135.00, description: 'Heavy duty drive gate post' },
  { id: 'm-post-4x4-10-hd', name: '4x4 x 10\' Wrought Iron Post (Heavy Wall)', category: 'Post', unit: 'each', cost: 158.00, description: 'Extra heavy wall thickness for large drive gates', imageUrl: 'https://quickshipaluminumfence.com/store/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/a/b/abp27b_black-aluminum-blank-post-2in-x-2in-x7ft_02.jpg' },
  { id: 'm-bracket', name: 'Wrought Iron Mounting Bracket', category: 'Hardware', unit: 'each', cost: 4.50, description: '4 per panel required' },
  { id: 'm-screw-self-tap', name: '1/4" x 1" Self Tapping Screw', category: 'Hardware', unit: 'each', cost: 0.35, description: 'Required for mounting brackets' },
  
  // 3ft Wrought Iron Panels
  { id: 'm-panel-3x8-2rft', name: '3x8 Wrought Iron - 2 Rail Flat Top', category: 'Metal', unit: 'each', cost: 150.00, description: 'Standard 2 rail flat top' },
  { id: 'm-panel-3x8-2rep', name: '3x8 Wrought Iron - 2 Rail Extended Pickets', category: 'Metal', unit: 'each', cost: 160.00, description: 'Extended pickets top' },
  { id: 'm-panel-3x8-3rr', name: '3x8 Wrought Iron - 3 Rail Racking', category: 'Metal', unit: 'each', cost: 175.00, description: '3 rail racking panel' },
  
  // 4ft Wrought Iron Panels
  { id: 'm-panel-4x8-2rft', name: '4x8 Wrought Iron - 2 Rail Flat Top', category: 'Metal', unit: 'each', cost: 165.00, description: 'Standard 2 rail flat top', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_KcCIlYvrgCjlATncP9RCW6bgzc6Etl3Baw&s' },
  { id: 'm-panel-4x8-2rep', name: '4x8 Wrought Iron - 2 Rail Extended Pickets', category: 'Metal', unit: 'each', cost: 175.00, description: 'Extended pickets top', imageUrl: 'https://cdn.gorilladash.com/images/media/4706798/citywide-macedon-group-spear-top-fencing-original-605a8ba05e349.jpg' },
  { id: 'm-panel-4x8-3rr', name: '4x8 Wrought Iron - 3 Rail Racking', category: 'Metal', unit: 'each', cost: 190.00, description: '3 rail racking panel' },

  // 5ft Wrought Iron Panels
  { id: 'm-panel-5x8-2rft', name: '5x8 Wrought Iron - 2 Rail Flat Top', category: 'Metal', unit: 'each', cost: 180.00, description: 'Standard 2 rail flat top', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_KcCIlYvrgCjlATncP9RCW6bgzc6Etl3Baw&s' },
  { id: 'm-panel-5x8-2rep', name: '5x8 Wrought Iron - 2 Rail Extended Pickets', category: 'Metal', unit: 'each', cost: 190.00, description: 'Extended pickets top', imageUrl: 'https://cdn.gorilladash.com/images/media/4706798/citywide-macedon-group-spear-top-fencing-original-605a8ba05e349.jpg' },
  { id: 'm-panel-5x8-3rr', name: '5x8 Wrought Iron - 3 Rail Racking', category: 'Metal', unit: 'each', cost: 205.00, description: '3 rail racking panel' },

  // 6ft Wrought Iron Panels
  { id: 'm-panel-6x8-2rft', name: '6x8 Wrought Iron - 2 Rail Flat Top', category: 'Metal', unit: 'each', cost: 195.00, description: 'Standard 2 rail flat top', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_KcCIlYvrgCjlATncP9RCW6bgzc6Etl3Baw&s' },
  { id: 'm-panel-6x8-2rep', name: '6x8 Wrought Iron - 2 Rail Extended Pickets', category: 'Metal', unit: 'each', cost: 205.00, description: 'Extended pickets top', imageUrl: 'https://cdn.gorilladash.com/images/media/4706798/citywide-macedon-group-spear-top-fencing-original-605a8ba05e349.jpg' },
  { id: 'm-panel-6x8-3rr', name: '6x8 Wrought Iron - 3 Rail Racking', category: 'Metal', unit: 'each', cost: 220.00, description: '3 rail racking panel' },

  // 7ft Wrought Iron Panels
  { id: 'm-panel-7x8-2rft', name: '7x8 Wrought Iron - 2 Rail Flat Top', category: 'Metal', unit: 'each', cost: 210.00, description: 'Standard 2 rail flat top' },
  { id: 'm-panel-7x8-2rep', name: '7x8 Wrought Iron - 2 Rail Extended Pickets', category: 'Metal', unit: 'each', cost: 220.00, description: 'Extended pickets top' },
  { id: 'm-panel-7x8-3rr', name: '7x8 Wrought Iron - 3 Rail Racking', category: 'Metal', unit: 'each', cost: 235.00, description: '3 rail racking panel' },
  
  // Farm Structure
  { id: 'f-post-t', name: '6\' Steel T-Post', category: 'Post', unit: 'each', cost: 8.25, description: 'Agricultural steel post', imageUrl: 'https://d2j6dbq0eux0bg.cloudfront.net/images/96378769/4289817609.jpg' },
  { id: 'f-wire-barbed', name: 'Barbed Wire Roll', category: 'Picket', unit: 'lf', cost: 0.22, description: '4-point barb', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqzM9pNZc71AOgs4XVvE_cm3wWDMsVyW_iGQ&s' },
  
  // Hardware & Fasteners
  { id: 'h-bracket-w', name: 'Wood Fence Bracket', category: 'Hardware', unit: 'each', cost: 1.45, description: 'Simpson Strong-Tie', imageUrl: 'https://ozcobp.com/wp-content/uploads/2021/09/50110_WAP-OZ-on-Fence_Lifestyle.jpg' },
  { id: 'h-lag-14', name: '1/4" Lag Screws (for brackets)', category: 'Fastener', unit: 'each', cost: 0.35, description: '1/4" galvanized lag', imageUrl: 'https://m.media-amazon.com/images/I/61ygv314ECL.jpg' },
  { id: 'h-screw-3', name: '3" Exterior Screws', category: 'Fastener', unit: 'box', cost: 28.00, description: '5lb box, deck rated', imageUrl: 'https://m.media-amazon.com/images/I/61ygv314ECL.jpg' },
  { id: 'h-nail-galv', name: 'Galv Ring-Shank Nails', category: 'Fastener', unit: 'each', cost: 0.005, description: '2" nails, price per nail', imageUrl: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcT3jXZREnFZgyniF8VdaLdhA9sn2VkSBBtvBDCISL30fG7dvZ3RtpeX5XBRadvkVk2asLsqNDqysLTBkhrSfNDoo-rjbbkBiM5u_rS6xL2C_NfAfHRHCQ8QCvlTIcOjsks9mI2x4FdUlQ&usqp=CAc' },
  { id: 'h-cl-band-tens', name: 'Tension Band', category: 'Hardware', unit: 'each', cost: 1.15, description: 'For terminal posts', imageUrl: 'https://www.thetoolsman.com/cdn/shop/files/Grainger_328521C.jpg?v=1713447124' },
  { id: 'h-cl-band-brace', name: 'Brace Band', category: 'Hardware', unit: 'each', cost: 1.25, description: 'For rail ends', imageUrl: 'https://images.thdstatic.com/productImages/a9846dc8-ac20-42cb-83d5-896a93dc00b6/svn/everbilt-chain-link-fence-accessories-328528eb-64_600.jpg' },
  { id: 'h-cl-tie', name: 'Aluminum Fence Ties', category: 'Hardware', unit: 'box', cost: 14.50, description: '100 count', imageUrl: 'https://fencesupplyinc.com/wp-content/uploads/2023/12/fence-ties-9-ga-aluminum-8-1_2-inch_1.jpg' },
  
  // Gates
  { id: 'g-kit-3-hinge', name: '3-Hinge Wood Gate Kit', category: 'Gate', unit: 'each', cost: 42.00, description: 'Three heavy duty hinges specifically for wood walk gates', imageUrl: 'https://images.thdstatic.com/productImages/600a0d27-8862-4f49-bb9f-acee28329316/svn/afoxsos-specialty-hardware-59sa05453-64_600.jpg' },
  { id: 'g-kit-shark', name: 'Metal Frame Shark Hinge Gate Kit', category: 'Gate', unit: 'each', cost: 145.00, description: 'Heavy duty double gate kit', imageUrl: 'https://images.thdstatic.com/productImages/600a0d27-8862-4f49-bb9f-acee28329316/svn/afoxsos-specialty-hardware-59sa05453-64_600.jpg' },
  { id: 'g-latch-grav', name: 'Gravity Latch', category: 'Gate', unit: 'each', cost: 26.50, description: 'Pool-safe closure', imageUrl: 'https://static.grainger.com/rp/s/is/image/Grainger/1XMP1_AS01?$adapimg$&hei=536&wid=536' },
  { id: 'm-gate-4-pre', name: "4' Pre-made Wrought Iron Gate", category: 'Hardware', unit: 'each', cost: 185.00, description: 'Pre-fabricated metal gate' },
  { id: 'm-gate-8-double', name: "8' Double Wrought Iron Gate (4' x 2)", category: 'Hardware', unit: 'each', cost: 425.00, description: 'Double pre-fabricated metal gate kit' },
  { id: 'm-gate-end-6', name: "1.5\" x 6' Gate End", category: 'Structure', unit: 'each', cost: 22.50, description: 'For custom gate frame' },
  { id: 'h-barrel-hinge', name: 'Regular Barrel Hinge', category: 'Hardware', unit: 'pair', cost: 18.00, description: 'Heavy duty weld-on hinge' },
  { id: 'h-jbolt-hinge', name: 'J-Bolt Barrel Hinge 7" (PR)', category: 'Hardware', unit: 'each', cost: 48.00, description: 'Heavy duty weld-on hinges' },
  { id: 'g-frame-4ft-wood', name: '4\' Wood Gate Frame', category: 'Gate', unit: 'each', cost: 85.00 },
  { id: 'g-frame-6ft-wood', name: '6\' Wood Gate Frame', category: 'Gate', unit: 'each', cost: 125.00 },
  { id: 'g-latch-std', name: 'Standard Gate Latch', category: 'Hardware', unit: 'each', cost: 12.50 },
  
  // Installation
  { id: 'i-concrete-80', name: '80lb Concrete Mix (Standard)', category: 'Concrete', unit: 'bag', cost: 6.75, description: 'Standard setting', imageUrl: 'https://mobileimages.lowes.com/productimages/abbf972d-3b5f-47fb-94b2-2b7c4797cdaf/64515057.png?size=pdhism' },
  { id: 'i-concrete-maximizer', name: '80lb Maximizer Concrete', category: 'Concrete', unit: 'bag', cost: 8.50, description: 'High-yield concrete (.7 bags per post)', imageUrl: 'https://images.thdstatic.com/productImages/50170884-6014-4161-829d-486152a6547a/svn/sakrete-concrete-mix-100220671-64_1000.jpg' },
  { id: 'i-concrete-quickset', name: '50lb Quickset Concrete', category: 'Concrete', unit: 'bag', cost: 9.75, description: 'Fast-setting concrete (2 bags per post), 50lb bag', imageUrl: 'https://www.quikrete.com/images/products/fast-setting-concrete.png' },
  { id: 'i-foam', name: 'Post-Setting Foam', category: 'Concrete', unit: 'each', cost: 18.50, description: '2-part expanding foam', imageUrl: 'https://images.thdstatic.com/productImages/bc70eb23-9f73-4ce7-95b4-b048b422ee33/svn/sika-deck-parts-accessories-7116170-c3_600.jpg' },
  
  // Site Prep
  { id: 's-marking', name: 'Marking Paint & Stakes', category: 'SitePrep', unit: 'each', cost: 28.00, description: 'Layout supplies', imageUrl: 'https://www.gmesupply.com/media/catalog/product/m/a/marking-paint-web.jpg' },
  { id: 's-clearing', name: 'Vegetation Clearing', category: 'Labor', unit: 'hour', cost: 58.00, description: 'Brush and root removal', imageUrl: 'https://wemulch.com/wp-content/uploads/2022/09/fence_line_clearing_rocky_road_excavation.webp' },
  
  // Finishing
  { id: 'f-stain', name: 'Wood Sealant/Stain', category: 'Finishing', unit: 'gallon', cost: 52.00, description: 'Premium protection', imageUrl: 'https://m.media-amazon.com/images/I/91JiDMXNQfL._AC_UF350,350_QL80_.jpg' },
  { id: 'f-pre-stain', name: 'Factory Pre-Staining Service', category: 'Finishing', unit: 'lf', cost: 4.50, description: 'Factory applied finish per LF', imageUrl: 'https://m.media-amazon.com/images/I/91JiDMXNQfL._AC_UF350,350_QL80_.jpg' },
  { id: 'f-cap-trim', name: 'Top Trim (1x4x8)', category: 'Finishing', unit: 'each', cost: 6.50, description: '1x4-8ft top trim board', imageUrl: 'https://cedarcreekfences.com/wp-content/uploads/2020/01/11-Boxed-Posts-1024x768.jpg' },
  { id: 'f-double-trim-1x2', name: 'Double Trim (1x2x8)', category: 'Finishing', unit: 'each', cost: 4.25, description: '1x2-8ft trim for double trim application', imageUrl: 'https://cedarcreekfences.com/wp-content/uploads/2020/01/11-Boxed-Posts-1024x768.jpg' },
  { id: 'f-top-cap-2x6', name: 'Top Cap (2x6x12)', category: 'Finishing', unit: 'each', cost: 18.25, description: '2x6-12ft top cap rail', imageUrl: 'https://cedarcreekfences.com/wp-content/uploads/2020/01/11-Boxed-Posts-1024x768.jpg' },
  { id: 'f-shims', name: 'Leveling Shims', category: 'Consumable', unit: 'box', cost: 9.50, description: 'For rail alignment', imageUrl: 'https://i.ebayimg.com/images/g/SAcAAOSwTc5b6aQR/s-l1200.jpg' },
  
  // Pipe Fence (No-Climb)
  { id: 'p-stick-32', name: '2-3/8" x 32\' Sch 40 Pipe Stick', category: 'Rail', unit: 'each', cost: 219.20, description: 'Standard 32ft stick for cutting posts and rails' },
  { id: 'p-rail-238', name: '2-3/8" Sch 40 Top Rail Pipe', category: 'Rail', unit: 'lf', cost: 6.85, description: 'Structural galvanized pipe', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvhspKHpyyyB9YIYToMXfD01oTeYOHnSnpqA&s' },
  { id: 'p-post-238-6', name: '2-3/8" x 6\' Sch 40 Pipe Post', category: 'Post', unit: 'each', cost: 30.00, description: 'Pipe for 4ft fence (+2ft in ground)' },
  { id: 'p-post-238-7', name: '2-3/8" x 7\' Sch 40 Pipe Post', category: 'Post', unit: 'each', cost: 36.00, description: 'Pipe for 5ft fence (+2ft in ground)' },
  { id: 'p-post-238-8', name: '2-3/8" x 8\' Sch 40 Pipe Post', category: 'Post', unit: 'each', cost: 42.00, description: 'Pipe for 6ft fence (+2ft in ground)', imageUrl: 'https://us.evocdn.io/dealer/1459/catalog/product/images/171-5313-5332-1.webp' },
  { id: 'p-post-238-9', name: '2-3/8" x 9\' Sch 40 Pipe Post', category: 'Post', unit: 'each', cost: 48.00, description: 'Gate post for 6ft fence (+3ft in ground)' },
  { id: 'p-post-238-10', name: '2-3/8" x 10\' Sch 40 Pipe Post', category: 'Post', unit: 'each', cost: 54.00, description: 'Extra deep pipe (+4ft in ground)', imageUrl: 'https://us.evocdn.io/dealer/1459/catalog/product/images/171-5313-5332-1.webp' },
  { id: 'p-gate-4ft', name: "4' Pipe Fence Gate", category: 'Gate', unit: 'each', cost: 185.00, description: "4' single gate for pipe fence" },
  { id: 'p-gate-6ft', name: "6' Pipe Fence Gate", category: 'Gate', unit: 'each', cost: 245.00, description: "6' single gate for pipe fence" },
  { id: 'p-gate-12ft', name: "12' Pipe Fence Gate", category: 'Gate', unit: 'each', cost: 485.00, description: "12' single gate for pipe fence" },
  { id: 'p-gate-hardware-4ft', name: "4' Pipe Gate Hardware Kit", category: 'Hardware', unit: 'each', cost: 65.00 },
  { id: 'p-gate-hardware-6ft', name: "6' Pipe Gate Hardware Kit", category: 'Hardware', unit: 'each', cost: 85.00 },
  { id: 'p-gate-hardware-12ft', name: "12' Pipe Gate Hardware Kit", category: 'Hardware', unit: 'each', cost: 125.00 },
  { id: 'p-ez-tie', name: '2-3/8" EZ Tie', category: 'Hardware', unit: 'each', cost: 1.85, description: 'Wire-to-pipe fastener', imageUrl: 'https://ozcobp.com/wp-content/uploads/2021/09/50110_WAP-OZ-on-Fence_Lifestyle.jpg' },
  { id: 'p-paint-gal', name: 'Industrial Metal Paint (Gallon)', category: 'Hardware', unit: 'each', cost: 65.00, description: '1 gallon per 200ft coverage' },
  
  // No-Climb Wire Variations
  { id: 'p-wire-4-100-galv', name: "4' x 100' No-Climb Wire (Galv)", category: 'Picket', unit: 'each', cost: 195.00, description: 'Galvanized 100ft roll' },
  { id: 'p-wire-4-200-galv', name: "4' x 200' No-Climb Wire (Galv)", category: 'Picket', unit: 'each', cost: 375.00, description: 'Galvanized 200ft roll' },
  { id: 'p-wire-4-100-black', name: "4' x 100' No-Climb Wire (Black)", category: 'Picket', unit: 'each', cost: 245.00, description: 'Black coated 100ft roll' },
  { id: 'p-wire-4-200-black', name: "4' x 200' No-Climb Wire (Black)", category: 'Picket', unit: 'each', cost: 465.00, description: 'Black coated 200ft roll' },
  
  { id: 'p-wire-5-100-galv', name: "5' x 100' No-Climb Wire (Galv)", category: 'Picket', unit: 'each', cost: 245.00, description: 'Galvanized 100ft roll' },
  { id: 'p-wire-5-200-galv', name: "5' x 200' No-Climb Wire (Galv)", category: 'Picket', unit: 'each', cost: 475.00, description: 'Galvanized 200ft roll' },
  { id: 'p-wire-5-100-black', name: "5' x 100' No-Climb Wire (Black)", category: 'Picket', unit: 'each', cost: 295.00, description: 'Black coated 100ft roll' },
  { id: 'p-wire-5-200-black', name: "5' x 200' No-Climb Wire (Black)", category: 'Picket', unit: 'each', cost: 565.00, description: 'Black coated 200ft roll' },
  
  { id: 'p-wire-6-100-galv', name: "6' x 100' No-Climb Wire (Galv)", category: 'Picket', unit: 'each', cost: 295.00, description: 'Galvanized 100ft roll' },
  { id: 'p-wire-6-200-galv', name: "6' x 200' No-Climb Wire (Galv)", category: 'Picket', unit: 'each', cost: 575.00, description: 'Galvanized 200ft roll' },
  { id: 'p-wire-6-100-black', name: "6' x 100' No-Climb Wire (Black)", category: 'Picket', unit: 'each', cost: 345.00, description: 'Black coated 100ft roll' },
  { id: 'p-wire-6-200-black', name: "6' x 200' No-Climb Wire (Black)", category: 'Picket', unit: 'each', cost: 665.00, description: 'Black coated 200ft roll' },

  { id: 'p-paint-gal-structural', name: 'Structural Pipe Paint (Gallon)', category: 'Finishing', unit: 'gallon', cost: 72.00, description: 'Black satin finish', imageUrl: 'https://m.media-amazon.com/images/I/91JiDMXNQfL._AC_UF350,350_QL80_.jpg' },
  
  // Post Caps
  { id: 'pc-flat', name: 'Flat Cap', category: 'PostCap', unit: 'each', cost: 5.25, imageUrl: 'https://images.thdstatic.com/productImages/4bcc407b-7ae0-4300-8024-540e19b184a0/svn/redwood-stained-deck-post-caps-483969-64_600.jpg' },
  { id: 'pc-dome', name: 'Dome Cap', category: 'PostCap', unit: 'each', cost: 7.25, imageUrl: 'https://i5.walmartimages.com/seo/Universal-Forest-Products-106515-Gothic-Post-Top_430dfd8e-82a1-46c2-995e-13a418bab791.a479575ff19a8db23738c5346e194433.jpeg?odnHeight=2000&odnWidth=2000&odnBg=FFFFFF' },
  { id: 'pc-solar', name: 'Solar LED Cap', category: 'PostCap', unit: 'each', cost: 22.00, imageUrl: 'https://s.turbifycdn.com/aah/yhst-99239380869547/classy-caps-kingsbridge-white-dual-lighted-solar-post-cap-442.png' },
  { id: 'h-cane-bolt-24', name: '24" Black Cane Bolt', category: 'Hardware', unit: 'each', cost: 18.50, description: '24" Black drop rod for pipe or metal gates', imageUrl: 'https://images.thdstatic.com/productImages/38318721-a8e5-4f36-8c4d-b072a392268b/svn/everbilt-gate-hardware-15462-64_600.jpg' },
  { id: 'h-cane-bolt-48', name: '48" Black Cane Bolt', category: 'Hardware', unit: 'each', cost: 28.50, description: '48" Black drop rod for wood gates', imageUrl: 'https://images.thdstatic.com/productImages/38318721-a8e5-4f36-8c4d-b072a392268b/svn/everbilt-gate-hardware-15462-64_600.jpg' },
];

export const DEFAULT_ESTIMATE: Partial<Estimate> = {
  customerName: '',
  customerEmail: '',
  customerPhone: '',
  customerAddress: '',
  customerStreet: '',
  customerCity: '',
  customerState: '',
  customerZip: '',
  linearFeet: 100,
  corners: 2,
  height: 6,
  width: 8,
  runs: [],
  defaultStyleId: 'wood-privacy',
  defaultVisualStyleId: 'w-side',
  defaultHeight: 6,
  defaultColor: 'Natural',
  postCapId: 'pc-dome',
  hasCapAndTrim: false,
  gateCount: 1,
  gateStyleId: 'g-frame-4ft-wood',
  footingType: 'Cuboid',
  concreteType: 'Maximizer',
  postWidth: 6,
  postThickness: 6,
  hasSitePrep: false,
  needsClearing: false,
  needsMarking: true,
  obstacleRemoval: false,
  wastePercentage: 0,
  includeStain: false,
  markupPercentage: 20,
  taxPercentage: 8.25,
  deliveryFee: 50,
  pricingStrategy: 'best',
  selectedSupplier: '',
  manualQuantities: {},
  manualPrices: {},
  woodType: 'PT Pine',
  ironRails: '2 rail',
  ironTop: 'Flat top',
  topStyle: 'Dog Ear',
  isPreStained: false,
  hasRotBoard: true,
  defaultChainLinkGrade: 'Residential',
  defaultHasBottomRail: false,
};

export const DEFAULT_LABOR_RATES = {
  woodSideBySide6: 10,
  woodBoardOnBoard6: 12,
  woodSideBySide8: 12,
  woodBoardOnBoard8: 14,
  ironBoltUp: 8,
  ironWeldUp: 10,
  chainLink: 9,
  pipeFence: 12,
  topCap: 1,
  additionalRailPipe: 2,
  demo: 2,
  washAndStain: 0.8, // per sq ft
  gateWeldedFrame: 150,
  gateWoodWalk: 100,
  gateWoodDrive: 150,
  gateHangPreMade: 50,
  deliveryFee: 50,
};

export const FENCE_STYLES: FenceStyle[] = [
  {
    id: 'wood-privacy',
    name: 'Wood Privacy',
    type: 'Wood',
    description: 'Classic vertical wood privacy fence with cedar pickets.',
    availableHeights: [4, 6, 8],
    availableWidths: [8],
    availableColors: ['Natural', 'Cedar Stain', 'Dark Walnut'],
    visualStyles: [
      { id: 'w-side', name: 'Side by Side', priceModifier: 0, imageUrl: 'https://patriotfencekc.com/wp-content/gallery/aluminu/4-tall-solid-cedar-privacy-1x6x4.jpeg' },
      { id: 'w-bob', name: 'Board on Board', priceModifier: 0, imageUrl: 'https://atlantadecking.com/wp-content/uploads/2024/05/wood-fence-min-1024x680-1.jpg' },
      { id: 'w-horiz', name: 'Horizontal', priceModifier: 6.00, imageUrl: 'https://images.squarespace-cdn.com/content/v1/59df95b3f14aa1927776f821/1510695034637-67X6S6Y6Y6Y6Y6Y6Y6Y6/Horizontal+Fence+Austin' },
    ],
    calcLogic: { postsPerLF: 0.167, railsPerLF: 0.25, picketsPerLF: 2.2, concretePerPost: 0.7 },
    baseLaborRate: 14.50,
  },
  {
    id: 'chain-link',
    name: 'Chain Link',
    type: 'Chain Link',
    description: 'Durable and affordable galvanized steel mesh fence.',
    availableHeights: [4, 5, 6],
    availableWidths: [10],
    availableColors: ['Galvanized'],
    visualStyles: [
      { id: 'cl-std', name: "9ga Galv Mesh 6'", priceModifier: 0, imageUrl: 'https://image.made-in-china.com/318f0j00YTqfkIjPqHgb/-mp4.webp' },
      { id: 'cl-slat', name: 'Privacy Slats', priceModifier: 14.00, imageUrl: 'https://www.hooverfence.com/mas_assets/cache/image/1/0/a/0/x600-68106.Jpg' },
    ],
    calcLogic: { postsPerLF: 0.1, railsPerLF: 0.1, picketsPerLF: 1, concretePerPost: 1.2 },
    baseLaborRate: 9.50,
  },
  {
    id: 'aluminum-ornamental',
    name: 'Wrought Iron',
    type: 'Metal',
    description: 'Elegant wrought iron panels for a classic, durable look.',
    availableHeights: [3, 4, 5, 6, 7],
    availableWidths: [6, 8],
    availableColors: ['Black', 'Bronze', 'White'],
    visualStyles: [
      { id: 'm-2rft', name: 'Standard 2 Rail Flat Top', priceModifier: 0, imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_KcCIlYvrgCjlATncP9RCW6bgzc6Etl3Baw&s' },
      { id: 'm-2rep', name: '2 Rail Extended Pickets', priceModifier: 0, imageUrl: 'https://cdn.gorilladash.com/images/media/4706798/citywide-macedon-group-spear-top-fencing-original-605a8ba05e349.jpg' },
      { id: 'm-3rr', name: '3 Rail Racking', priceModifier: 0, imageUrl: 'https://quickshipaluminumfence.com/store/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/a/b/abp27b_black-aluminum-blank-post-2in-x-2in-x7ft_02.jpg' },
    ],
    calcLogic: { postsPerLF: 0.125, railsPerLF: 0, picketsPerLF: 0, concretePerPost: 1.5 },
    baseLaborRate: 19.50,
  },
  {
    id: 'pipe-no-climb',
    name: 'Pipe Fence',
    type: 'Pipe',
    description: 'Structural pipe with premium no-climb wire.',
    availableHeights: [4, 5, 6],
    availableWidths: [4, 6, 8, 12],
    availableColors: ['Raw', 'Black', 'White', 'Green'],
    visualStyles: [
      { id: 'p-std', name: 'Standard No-Climb', priceModifier: 0, imageUrl: 'https://images.squarespace-cdn.com/content/v1/5c868019778897587747e4eb/1585257929424-C9D6W74ZJ8M9R7P6X0B3/Pipe+Fence+with+No+Climb+Wire' },
      { id: 'p-black', name: 'Black No-Climb', priceModifier: 45, imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_x_O-Ym9z-H_v_y_-_-_-_-y-_-_-_-y-_' }
    ],
    calcLogic: { postsPerLF: 0.125, railsPerLF: 1, picketsPerLF: 1, concretePerPost: 2 },
    baseLaborRate: 12.00,
  },
];
